export const ADD_TO_CART='ADD_TO_CART'
export const REMOVE_FROM_CART='REMOVE_FROM_CART'
export const SELL_PRODUCT='SELL_PRODUCT'
export const QUANTITY_CHANGER='QUANTITY_CHANGER'
export const ADD_TO_FAVORITES='ADD_TO_FAVORITES'

